### ISSUE TITLE
UserTraits after serialize returns user_traits instead user.traits

### ISSUE THREAD

**Issue by gianaugusto** [castle/castle-dotnet#66]
Hello

In the [documentation](https://docs.castle.io/docs/migrating-from-legacy-apis#step-2-passing-the-request-token-to-the-legacy-apis) the object user_traits was moved to user.traits, but current [serializer](https://github.com/castle/castle-dotnet/blob/develop/src/Castle.Sdk/Infrastructure/Json/JsonForCastle.cs#L14) return object in old format user_traits, and this behaviour break all consumers for .net sdk.

**Comment by ssachd3va** [comment]
Unable to create request token using castle-sdk on .NET framework.

I am designing a plugin on .NET Framework and want to use castle-sdk for creating a request token, which will be used every time a user log in. Surfed around the web and found there are inbuilt functions available for browser-sdk(web), android and iOS. But I couldn't find any equivalent function on .NET framework.

iOS code:
![image](https://user-images.githubusercontent.com/108451424/202089014-f398693f-20e9-4c61-84a8-e68b18521ce0.png)

Android code: 
![image](https://user-images.githubusercontent.com/108451424/202089247-9e5831c6-4f71-4705-98fd-c704a285de38.png)

**Comment by fgranacha** [comment]
@gianaugusto this shouldn't be a problem in the newer versions, if you still have this issue please open a new issue.
